name = "Multipactor"
uuid = "f5b33793-ae87-451d-8f1a-78cbcd2157c7"
authors = ["Andres Berenguer <anberalon@gmail.com> and contributors"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
JSON = "0.21"
julia = "1.5.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
